// USER ACTION TYPES //
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

// GAME ACTION TYPES //
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const SET_CURRENT_QUESTION_INDEX = 'SET_CURRENT_QUESTION_INDEX';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const SET_TIME_LEFT = 'SET_TIME_LEFT';
export const SET_GAME_STATE = 'SET_GAME_STATE';
export const SET_COUNTDOWN = 'SET_COUNTDOWN';
export const SET_POWER_UPS = 'SET_POWER_UPS';
export const SET_ACTIVE_POWER_UP = 'SET_ACTIVE_POWER_UP';
export const END_GAME = 'END_GAME';
export const UPDATE_PLAYER_STATS = 'UPDATE_PLAYER_STATS';






