nixPkgs = [
    "nodejs-20_x",
    "npm",
    "postgresql",
    "python3",
    "python3Packages.flask",
    "python3Packages.gunicorn",
    "python3Packages.flask-sqlalchemy",
    "python3Packages.psycopg2",
    "python3Packages.flask-migrate",
    "python3Packages.flask-cors",
    "python3Packages.python-dotenv"
]

[phases.build]
cmds = [
    "cd frontend/mythology-trivia-game && npm install && npm run build",
    "mv frontend/mythology-trivia-game/build backend/static"
]

[start]
cmd = "gunicorn 'app:app' --bind=0.0.0.0:$PORT"
workdir = "backend"