[phases.setup]
nixPkgs = [
    "postgresql",
    "python3",
    "python3Packages.pip",
    "python3Packages.virtualenv"
]

[phases.install]
path = "backend"
cmds = [
    "python3 -m venv /app/venv",
    ". /app/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
    "cd ../frontend && npm install && npm run build",
    "mv ../frontend/build ./static"
]

[start]
cmd = ". /app/venv/bin/activate && gunicorn app:app"
workdir = "backend"