[phases.setup]
nixPkgs = [
    "postgresql",
    "python3",
    "python3Packages.pip"  # Include pip as a package
]

[phases.install]
path = "backend"
cmds = [
    "python3 -m pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
    "cd ../frontend && npm install && npm run build",
    "mv ../frontend/build ./static"
]

[start]
cmd = "gunicorn app:app"
workdir = "backend"