[phases.setup]
nixPkgs = [
    "python310",
    "nodejs",
    "postgresql",
    "python310Packages.flask",
    "python310Packages.gunicorn",
    "python310Packages.flask-sqlalchemy",
    "python310Packages.psycopg2",
    "python310Packages.flask-migrate",
    "python310Packages.flask-cors",
    "python310Packages.python-dotenv"
]

[phases.build]
cmds = [
    "npm install --prefix frontend/mythology-trivia-game",
    "npm run build --prefix frontend/mythology-trivia-game",
    "mkdir -p backend/static",
    "mv frontend/mythology-trivia-game/build/* backend/static/"
]

[start]
cmd = "gunicorn backend.app:app --bind=0.0.0.0:$PORT"
workdir = "backend"