[phases.setup]
nixPkgs = [
    "postgresql",
    "python3",
    "python3Packages.flask",
    "python3Packages.gunicorn",
    "python3Packages.flask_sqlalchemy",  # Use underscore for package names
    "python3Packages.psycopg2",
    "python3Packages.flask_migrate",
    "python3Packages.flask_cors",
    "python3Packages.python_dotenv",
    "nodejs",
    "npm"
]

[phases.build]
cmds = [
    "cd frontend/mythology-trivia && npm install && npm run build",
    "mv frontend/mythology-trivia/build backend/static"
]

[start]
cmd = "gunicorn 'app:app' --bind=0.0.0.0:$PORT"
workdir = "backend"