[phases.setup]
nixPkgs = ["python3", "python3-pip", "postgresql"]

[phases.install]
path = "backend"
cmds = [
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
    "cd ../frontend && npm install && npm run build",
    "mv ../frontend/build ./static"
]

[start]
cmd = "gunicorn app:app"
workdir = "backend"