"""Add active_power_ups to User model

Revision ID: 28712e8044da
Revises: dda3e73b45bc
Create Date: 2024-09-19 00:33:05.773032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28712e8044da'
down_revision = 'dda3e73b45bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_power_ups', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active_power_ups')

    # ### end Alembic commands ###
