"""added dailychallenge check with boolean

Revision ID: 2b77aadbbf00
Revises: 62acc58fdc30
Create Date: 2024-09-16 17:51:41.345116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b77aadbbf00'
down_revision = '62acc58fdc30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_challenge_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('daily_challenge_completed')

    # ### end Alembic commands ###
