"""Add user_daily_challenges table

Revision ID: 62acc58fdc30
Revises: bd7825080ab0
Create Date: 2024-09-16 16:11:18.749483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62acc58fdc30'
down_revision = 'bd7825080ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_daily_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('date_answered', sa.DateTime(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_daily_challenges')
    # ### end Alembic commands ###
