"""added powerup model and user-powerup relationship

Revision ID: 6e1021e1f1a1
Revises: b51594ee80c8
Create Date: 2024-09-11 18:58:46.198805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1021e1f1a1'
down_revision = 'b51594ee80c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('powerup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_powerups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('powerup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['powerup_id'], ['powerup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'powerup_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_powerups')
    op.drop_table('powerup')
    # ### end Alembic commands ###
