"""added user_powerup association table

Revision ID: bd7825080ab0
Revises: c92fbb76a404
Create Date: 2024-09-14 18:10:37.091969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7825080ab0'
down_revision = 'c92fbb76a404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_powerup',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('powerup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['powerup_id'], ['powerup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'powerup_id')
    )
    op.drop_table('user_powerups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_powerups',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('powerup_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['powerup_id'], ['powerup.id'], name='user_powerups_powerup_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_powerups_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'powerup_id', name='user_powerups_pkey')
    )
    op.drop_table('user_powerup')
    # ### end Alembic commands ###
