"""remove Challenge, ChallengeResponse, and ChallengeQuestion tables

Revision ID: c92fbb76a404
Revises: 2b667636581e
Create Date: 2024-09-14 15:47:44.196656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c92fbb76a404'
down_revision = '2b667636581e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge_question')
    op.drop_table('challenge_response')
    op.drop_table('challenge')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('challenge_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('theme', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('difficulty', postgresql.ENUM('easy', 'medium', 'hard', name='DifficultyEnum'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name='challenge_creator_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='challenge_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('challenge_response',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name='challenge_response_challenge_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='challenge_response_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='challenge_response_pkey')
    )
    op.create_table('challenge_question',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name='challenge_question_challenge_id_fkey'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='challenge_question_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='challenge_question_pkey')
    )
    # ### end Alembic commands ###
