"""added activation conditions usage limit to power up model, updated association table

Revision ID: dda3e73b45bc
Revises: 2b77aadbbf00
Create Date: 2024-09-18 18:34:29.569442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda3e73b45bc'
down_revision = '2b77aadbbf00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('powerup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activation_conditions', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('usage_limit', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_powerup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_used', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('earned_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_powerup', schema=None) as batch_op:
        batch_op.drop_column('earned_at')
        batch_op.drop_column('is_used')

    with op.batch_alter_table('powerup', schema=None) as batch_op:
        batch_op.drop_column('usage_limit')
        batch_op.drop_column('activation_conditions')

    # ### end Alembic commands ###
